# SITE CONFIGURATION
baseurl: ""
url: "https://liujq.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Jackin's Blog"
  avatar: assets/img/avatar.png
  favicon: assets/myfavicon.ico
  gravatar: 48B653DCAC99BBF259AE99FDC88E661B # Email MD5 hash
  description: "A website with blog posts and pages about Android" # used by search engines

  # Header and footer text
  header_text: #two or three lines to describe your site 
    <p>Keep studying, keep wise.</p>
  header_text_feature_image: assets/img/feature/triangular.jpeg
  footer_text: Copyright 2018 Jackin 
   <p>Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a></p>

  # Header for collections
  collection_translations_header_text: <p>Those excellent articles you will enjoy</p>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: liujianqiao39870@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "LiuJQ"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: Jackin_Q # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: "UA-117927654-1"
  disqus_shortname: liujq
  katex: true # Enable if using math markup
  translations: true
  portfolio: true
  search: true
  tags: true

  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

  translations:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
